config/routes.rb
Polyfit::Application.routes.draw do
  root to: 'regiment_requests#new'

  devise_for :users
  
  resources :user_favorites

  devise_scope :user do
    get "/signin", to: "devise/sessions#new"
    get "/signout", to: "devise/sessions#destroy"
    get "/signup", to: "devise/registrations#new"

    get '/profile/edit', to: 'devise/registrations#edit'
  end

  get 'profile/show', to: 'users#show'

  get '/test', to: 'static#test'
  get '/style', to: 'static#style'

  get '/about', to: 'static#about'
  get '/copyright', to: 'static#copyright'
  get '/privacy', to: 'static#privacy'
  get '/terms', to: 'static#terms'
  get '/faq', to: 'static#faq'
  get '/support', to: 'static#support'

  resources :regiment_requests
  
  resources :regiment_exercises

  resources :regiments

  resources :exercises

  resources :users

end

app/models/regiment_request.rb
class RegimentRequest < ActiveRecord::Base
end

app/controllers/regiment_requests_controller.rb
class RegimentRequestsController < ApplicationController
  before_action :set_regiment_request, only: [:show, :edit, :update, :destroy]

  # GET /regiment_requests
  # GET /regiment_requests.json
  def index
    @regiment_requests = RegimentRequest.all
  end

  # GET /regiment_requests/1
  # GET /regiment_requests/1.json
  def show
  end

  # GET /regiment_requests/new
  def new
    @regiment_request = RegimentRequest.new
  end

  # GET /regiment_requests/1/edit
  def edit
  end

  # POST /regiment_requests
  # POST /regiment_requests.json
  def create
    @regiment_request = RegimentRequest.new(regiment_request_params)

    respond_to do |format|
      if @regiment_request.save
        format.html { redirect_to @regiment_request, notice: 'Regiment request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @regiment_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @regiment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regiment_requests/1
  # PATCH/PUT /regiment_requests/1.json
  def update
    respond_to do |format|
      if @regiment_request.update(regiment_request_params)
        format.html { redirect_to @regiment_request, notice: 'Regiment request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @regiment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regiment_requests/1
  # DELETE /regiment_requests/1.json
  def destroy
    @regiment_request.destroy
    respond_to do |format|
      format.html { redirect_to regiment_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regiment_request
      @regiment_request = RegimentRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regiment_request_params
      params.require(:regiment_request).permit(:opt0, :opt1, :opt2, :opt3, :opt4, :opt5, :opt6, :opt7)
    end
end

app/helpers/regiment_requests_helper.rb
module RegimentRequestsHelper
end

app/views/regiment_requests/_form.html.erb
<%= form_for(@regiment_request) do |f| %>
  <% if @regiment_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regiment_request.errors.count, "error") %> prohibited this regiment_request from being saved:</h2>

      <ul>
      <% @regiment_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :opt0 %><br>
    <%= f.text_field :opt0 %>
  </div>
  <div class="field">
    <%= f.label :opt1 %><br>
    <%= f.text_field :opt1 %>
  </div>
  <div class="field">
    <%= f.label :opt2 %><br>
    <%= f.text_field :opt2 %>
  </div>
  <div class="field">
    <%= f.label :opt3 %><br>
    <%= f.text_field :opt3 %>
  </div>
  <div class="field">
    <%= f.label :opt4 %><br>
    <%= f.text_field :opt4 %>
  </div>
  <div class="field">
    <%= f.label :opt5 %><br>
    <%= f.text_field :opt5 %>
  </div>
  <div class="field">
    <%= f.label :opt6 %><br>
    <%= f.text_field :opt6 %>
  </div>
  <div class="field">
    <%= f.label :opt7 %><br>
    <%= f.text_field :opt7 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regiment_requests/edit.html.erb
<h1>Editing regiment_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @regiment_request %> |
<%= link_to 'Back', regiment_requests_path %>

app/views/regiment_requests/index.html.erb
<h1>Listing regiment_requests</h1>

<table>
  <thead>
    <tr>
      <th>Opt0</th>
      <th>Opt1</th>
      <th>Opt2</th>
      <th>Opt3</th>
      <th>Opt4</th>
      <th>Opt5</th>
      <th>Opt6</th>
      <th>Opt7</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @regiment_requests.each do |regiment_request| %>
      <tr>
        <td><%= regiment_request.opt0 %></td>
        <td><%= regiment_request.opt1 %></td>
        <td><%= regiment_request.opt2 %></td>
        <td><%= regiment_request.opt3 %></td>
        <td><%= regiment_request.opt4 %></td>
        <td><%= regiment_request.opt5 %></td>
        <td><%= regiment_request.opt6 %></td>
        <td><%= regiment_request.opt7 %></td>
        <td><%= link_to 'Show', regiment_request %></td>
        <td><%= link_to 'Edit', edit_regiment_request_path(regiment_request) %></td>
        <td><%= link_to 'Destroy', regiment_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Regiment request', new_regiment_request_path %>

app/views/regiment_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Opt0:</strong>
  <%= @regiment_request.opt0 %>
</p>

<p>
  <strong>Opt1:</strong>
  <%= @regiment_request.opt1 %>
</p>

<p>
  <strong>Opt2:</strong>
  <%= @regiment_request.opt2 %>
</p>

<p>
  <strong>Opt3:</strong>
  <%= @regiment_request.opt3 %>
</p>

<p>
  <strong>Opt4:</strong>
  <%= @regiment_request.opt4 %>
</p>

<p>
  <strong>Opt5:</strong>
  <%= @regiment_request.opt5 %>
</p>

<p>
  <strong>Opt6:</strong>
  <%= @regiment_request.opt6 %>
</p>

<p>
  <strong>Opt7:</strong>
  <%= @regiment_request.opt7 %>
</p>

<%= link_to 'Edit', edit_regiment_request_path(@regiment_request) %> |
<%= link_to 'Back', regiment_requests_path %>