config/routes.rb
Polyfit::Application.routes.draw do
  root to: 'regiment_requests#new'

  devise_for :users
  
  resources :user_favorites

  devise_scope :user do
    get "/signin", to: "devise/sessions#new"
    get "/signout", to: "devise/sessions#destroy"
    get "/signup", to: "devise/registrations#new"

    get '/profile/edit', to: 'devise/registrations#edit'
  end

  get 'profile/show', to: 'users#show'

  get '/test', to: 'static#test'
  get '/style', to: 'static#style'

  get '/about', to: 'static#about'
  get '/copyright', to: 'static#copyright'
  get '/privacy', to: 'static#privacy'
  get '/terms', to: 'static#terms'
  get '/faq', to: 'static#faq'
  get '/support', to: 'static#support'

  resources :regiment_requests
  
  resources :regiment_exercises

  resources :regiments

  resources :exercises

  resources :users

end

app/models/regiment.rb
class Regiment < ActiveRecord::Base
  has_many :regiment_exercises
  has_many :exercises, through: :regiment_exercises

  has_many :user_favorites
  has_many :users, through: :user_favorites
end

app/controllers/regiments_controller.rb
class RegimentsController < ApplicationController
  before_action :set_regiment, only: [:show, :edit, :update, :destroy]

  # GET /regiments
  # GET /regiments.json
  def index
    @regiments = Regiment.all
  end

  # GET /regiments/1
  # GET /regiments/1.json
  def show
  end

  # GET /regiments/new
  def new
    @regiment = Regiment.new
  end

  # GET /regiments/1/edit
  def edit
  end

  # POST /regiments
  # POST /regiments.json
  def create
    @regiment = Regiment.new(regiment_params)
    update_regiment_exercises
    respond_to do |format|
      if @regiment.save
        format.html { redirect_to @regiment, notice: 'Regiment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @regiment }
      else
        format.html { render action: 'new' }
        format.json { render json: @regiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regiments/1
  # PATCH/PUT /regiments/1.json
  def update
    respond_to do |format|
      if @regiment.update(regiment_params)
        update_regiment_exercises
        format.html { redirect_to @regiment, notice: 'Regiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @regiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regiments/1
  # DELETE /regiments/1.json
  def destroy
    @regiment.destroy
    respond_to do |format|
      format.html { redirect_to regiments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regiment
      @regiment = Regiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regiment_params
      params.require(:regiment).permit(:name, :description)
    end

    # Returns a list of the exercise id's in the form of an array (will never be nil)
    # Since it doesn't use the require/permit stuff, I am not sure how safe it is...
    def exercise_list_param
      return params[:exercises].to_a
    end

    # Helper method to update the exercises in each regiment, given a list of the exercise_id's in params[:regiment][:exercises]
    # Note that the orders will be zero-indexed
    def update_regiment_exercises
      exercise_list_param.each_with_index do |re_id, i|
        exercise = Exercise.find(re_id)
        RegimentExercise.create!(regiment: @regiment, exercise: exercise, order: i, reps: 0);
      end
    end
end

app/helpers/regiments_helper.rb
module RegimentsHelper
end

app/views/regiments/_form.html.erb
<%= form_for(@regiment) do |f| %>
  <% if @regiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regiment.errors.count, "error") %> prohibited this regiment from being saved:</h2>

      <ul>
      <% @regiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= select_tag :exercises, options_for_select(Exercise.all.collect { |x| [x.name, x.id, selected: @regiment.exercises.include?(x)] }), { include_hidden: false, multiple: true } %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regiments/edit.html.erb
<h1>Editing regiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @regiment %> |
<%= link_to 'Back', regiments_path %>

app/views/regiments/index.html.erb
<h1>Listing regiments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @regiments.each do |regiment| %>
      <tr>
        <td><%= regiment.name %></td>
        <td><%= regiment.description %></td>
        <td><%= link_to 'Show', regiment %></td>
        <td><%= link_to 'Edit', edit_regiment_path(regiment) %></td>
        <td><%= link_to 'Destroy', regiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Regiment', new_regiment_path %>

app/views/regiments/new.html.erb
<h1>New regiment</h1>

<%= render 'form' %>

<%= link_to 'Back', regiments_path %>

app/views/regiments/show.html.erb
<script>
  $(function() {
    $("#accordion").accordion();
  });
</script>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @regiment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @regiment.description %>
</p>

<div id="accordion">
  <% @regiment.exercises.each_with_index do |exercise, i| %>
    <h3><%= "#{i}) #{exercise.name}" %></h3>
    <div>
      <p>
        <%= exercise.description %>
      </p>
      <p>
        <%= video_tag exercise.video.url, controls: true, size: '320x240' %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_regiment_path(@regiment) %> |
<%= link_to 'Back', regiments_path %>