config/routes.rb
Polyfit::Application.routes.draw do
  root to: 'regiment_requests#new'

  devise_for :users
  
  resources :user_favorites

  devise_scope :user do
    get "/signin", to: "devise/sessions#new"
    get "/signout", to: "devise/sessions#destroy"
    get "/signup", to: "devise/registrations#new"

    get '/profile/edit', to: 'devise/registrations#edit'
  end

  get 'profile/show', to: 'users#show'

  get '/test', to: 'static#test'
  get '/style', to: 'static#style'

  get '/about', to: 'static#about'
  get '/copyright', to: 'static#copyright'
  get '/privacy', to: 'static#privacy'
  get '/terms', to: 'static#terms'
  get '/faq', to: 'static#faq'
  get '/support', to: 'static#support'

  resources :regiment_requests
  
  resources :regiment_exercises

  resources :regiments

  resources :exercises

  resources :users

end

app/models/user_favorite.rb
class UserFavorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :regiment
end

app/controllers/user_favorites_controller.rb
class UserFavoritesController < ApplicationController
  before_action :set_user_favorite, only: [:show, :edit, :update, :destroy]

  # GET /user_favorites
  # GET /user_favorites.json
  def index
    @user_favorites = UserFavorite.all
  end

  # GET /user_favorites/1
  # GET /user_favorites/1.json
  def show
  end

  # GET /user_favorites/new
  def new
    @user_favorite = UserFavorite.new
  end

  # GET /user_favorites/1/edit
  def edit
  end

  # POST /user_favorites
  # POST /user_favorites.json
  def create
    @user_favorite = UserFavorite.new(user_favorite_params)

    respond_to do |format|
      if @user_favorite.save
        format.html { redirect_to @user_favorite, notice: 'User favorite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_favorite }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_favorites/1
  # PATCH/PUT /user_favorites/1.json
  def update
    respond_to do |format|
      if @user_favorite.update(user_favorite_params)
        format.html { redirect_to @user_favorite, notice: 'User favorite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_favorites/1
  # DELETE /user_favorites/1.json
  def destroy
    @user_favorite.destroy
    respond_to do |format|
      format.html { redirect_to user_favorites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_favorite
      @user_favorite = UserFavorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_favorite_params
      params[:user_favorite]
    end
end

app/helpers/user_favorites_helper.rb
module UserFavoritesHelper
end

app/views/user_favorites/_form.html.erb
<%= form_for(@user_favorite) do |f| %>
  <% if @user_favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_favorite.errors.count, "error") %> prohibited this user_favorite from being saved:</h2>

      <ul>
      <% @user_favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_favorites/edit.html.erb
<h1>Editing user_favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_favorite %> |
<%= link_to 'Back', user_favorites_path %>

app/views/user_favorites/index.html.erb
<h1>Listing user_favorites</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_favorites.each do |user_favorite| %>
      <tr>
        <td><%= link_to 'Show', user_favorite %></td>
        <td><%= link_to 'Edit', edit_user_favorite_path(user_favorite) %></td>
        <td><%= link_to 'Destroy', user_favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User favorite', new_user_favorite_path %>

app/views/user_favorites/new.html.erb
<h1>New user_favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', user_favorites_path %>

app/views/user_favorites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_favorite_path(@user_favorite) %> |
<%= link_to 'Back', user_favorites_path %>